### ISSUE TITLE
avoid early shut off of heaters on temporary errors

### ISSUE THREAD

**Issue by freddyrios** [copenhagenatomics/CA_DataUploader#146]
**context:**
filters interplay with oven control in the following way:
1. if oven control does not see a valid temperature value during 2 seconds, then the corresponding heater can't turn on + if it was off it would turn off early
2. when using a 3 seconds filter, the oven control only starts seeing the error after the 3 seconds, so in total that's 5 seconds before it prevents the heater from turning on
3. the 2 seconds limit also applies to temperature boards that stop reporting data

Additionally we have now p control, that uses a control period to decide to make a new actuation. However, as seen above, if we stop getting temperature data temporarily we shut off the heater early. 

**Proposal:** 
We should consider keeping the actuation of the current control period unchanged and only on the next control period prevent actuation if we don't have temperature data (effectively postponing it to the next time when we get temperature data again). 

**Pros**: more stable actuations even in the face of frequent errors reading the thermocouples
**Cons**: the temperature can overshoot more than it normally would, if it was about to overshoot this cycle before we lost the temperature data i.e. as we normally have the extra behavior of stopping heating early if we reached the target temperature (which might be something we should revisit though).

**Comment by lasse-tarp-CA** [comment]
@freddyrios Lets disgusts this on DS or just after DS
