### ISSUE TITLE
Filter on items VFD items

### ISSUE THREAD

**Issue by copenhagenatomics** [copenhagenatomics/CA_DataUploader#47]
The Filter command in IO.conf give an error if it refer to something which is not mentioned in the IO.conf
But for the VFD it has fx. 9 outputs which all have different names. 

This this filter does not work:
Filter;MotorAmp;Triangle;2;AmpOut;hidesource

Because AmpOut is not specifically named in the IO.conf file.  But it is in the vector.

**Comment by freddyrios** [comment]
@copenhagenatomics this should be working since #35 got merged
