### ISSUE TITLE
lack of MCUBoard dispose at SerialNumberMapper.Dispose

### ISSUE THREAD

**Issue by freddyrios** [copenhagenatomics/CA_DataUploader#78]
Normally the SerialNumberMapper.Dispose should be disposing the boards it initialized in its McuBoards field. However, the way the overall design runs has the subsystems run some shut down commands against the boards shortly after their Dispose its called, which in turns means that SerialNumberMapper.Dispose may be called before those commands have finished running.

We need to make it so that SerialNumberMapper.Dispose runs when the disposed subsystems have exited. One option is to make sure there is some signalling mecanism that surrounds all the subsystems made in a way that it is signaled when all is done + in a way that still works when the dispose chain is triggered due to exceptions.

**Comment by LarsWithCA** [comment]
not relevant anymore. closing.
